name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Cache Composer Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Cache npm Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: SSH into Hetzner Server and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@116.203.89.77 << 'EOF'
          cd /root/hetzner-hosting/projects/jobmosaic
          git pull
          cd /root/hetzner-hosting
          docker compose down
          docker compose build
          docker compose up -d
          docker exec -it jobmosaic_app php artisan migrate --force
          docker exec -it jobmosaic_app php artisan config:cache
          docker exec -it jobmosaic_app npm install
          docker exec -it jobmosaic_app npm run build
          EOF

      # - name: Send deployment notification
      #   uses: softprops/gmail@v1
      #   with:
      #     to: 'your_email@example.com'
      #     from: 'your_email@example.com'
      #     subject: 'Deployment to Hetzner Complete'
      #     body: 'Your deployment to Hetzner has been completed successfully.'
      #   env:
      #     GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      #     GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      #     GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
      #     GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
      #     GMAIL_REDIRECT_URI: ${{ secrets.GMAIL_REDIRECT_URI }}
      #     GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
