name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_HOST: 116.203.89.77
      PROJECT_PATH: /root/hetzner-hosting/projects/jobmosaic
      DOCKER_PATH: /root/hetzner-hosting
      REPO_URL: git@github.com:${{ github.repository }}.git

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ env.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Cache npm Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Deploy to Hetzner
        run: |
          ssh root@${{ env.SSH_HOST }} \
          PROJECT_PATH='${{ env.PROJECT_PATH }}' \
          DOCKER_PATH='${{ env.DOCKER_PATH }}' \
          REPO_URL='${{ env.REPO_URL }}' \
          'bash -s' << 'EOT'
          set -e
          echo "Starting deployment..."

          echo "Debug: Current environment"
          echo "PROJECT_PATH: $PROJECT_PATH"
          echo "DOCKER_PATH: $DOCKER_PATH"
          echo "REPO_URL: $REPO_URL"

          # Create project directory if it doesn't exist
          mkdir -p "$PROJECT_PATH"

          # Check if git repository exists
          if [ ! -d "$PROJECT_PATH/.git" ]; then
              echo "Initializing new repository..."
              rm -rf "$PROJECT_PATH"/*
              git clone "$REPO_URL" "$PROJECT_PATH"
              cd "$PROJECT_PATH"
          else
              echo "Repository exists, pulling latest changes..."
              cd "$PROJECT_PATH"
              git fetch --all
              git reset --hard origin/main
          fi

          echo "Navigate to docker directory"
          cd "$DOCKER_PATH"

          echo "Rebuild and restart containers"
          docker compose down
          docker compose build
          docker compose up -d

          # Pass environment variables to the container
          export DB_CONNECTION=${{ secrets.DB_CONNECTION }}
          export DB_HOST=${{ secrets.DB_HOST }}
          export DB_PORT=${{ secrets.DB_PORT }}
          export DB_DATABASE=${{ secrets.DB_DATABASE }}
          export DB_USERNAME=${{ secrets.DB_USERNAME }}
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          export MAIL_MAILER=${{ secrets.MAIL_MAILER }}
          export MAIL_HOST=${{ secrets.MAIL_HOST }}
          export MAIL_PORT=${{ secrets.MAIL_PORT }}
          export MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
          export MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          export MAIL_ENCRYPTION=${{ secrets.MAIL_ENCRYPTION }}
          export MAIL_FROM_ADDRESS=${{ secrets.MAIL_FROM_ADDRESS }}
          export MAIL_FROM_NAME=${{ secrets.MAIL_FROM_NAME }}
          export OPEN_CAGE_KEY=${{ secrets.OPEN_CAGE_KEY }}
          export NOCAPTCHA_SITEKEY=${{ secrets.NOCAPTCHA_SITEKEY }}
          export NOCAPTCHA_SECRET=${{ secrets.NOCAPTCHA_SECRET }}

          echo "Deployment completed successfully!"
          EOT

      - name: Wait for jobmosaic_app to be healthy
        run: |
          for i in {1..15}; do
            if ssh root@${{ env.SSH_HOST }} "cd /root/hetzner-hosting && docker inspect --format='{{.State.Health.Status}}' jobmosaic_app" | grep "healthy"; then
              echo "jobmosaic_app is healthy."
              break
            else
              echo "Waiting for jobmosaic_app to become healthy..."
              sleep 10  # Wait for 10 seconds before checking again
            fi
          done

      - name: Run Laravel and NPM commands
        run: |
          ssh root@${{ env.SSH_HOST }} << 'EOF'
          set -e  # Exit immediately if a command exits with a non-zero status
          cd /root/hetzner-hosting
          echo "Current directory: $(pwd)"
          echo "Listing all running containers..."
          docker container ls
          echo "checking health..."
          docker inspect --format='{{.State.Health.Status}}' jobmosaic_app
          echo "Running Laravel migrations..."
          docker compose exec -T jobmosaic_app php artisan migrate --force
          echo "Clearing cache..."
          docker compose exec -T jobmosaic_app php artisan config:cache
          docker compose exec -T jobmosaic_app php artisan route:cache
          docker compose exec -T jobmosaic_app php artisan view:cache



          echo "Installing NPM dependencies..."
          docker compose exec -T jobmosaic_app npm ci

          echo "Building the application..."
          docker compose exec -T jobmosaic_app npm run build
          EOF

      - name: Verify Deployment
        run: |
          ssh root@${{ env.SSH_HOST }} "docker compose ps"
